services:
  postgres:
    image: postgres:17.6-alpine3.22
    container_name: springboot-reservation-postgres
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yu71 -d reservation" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
